version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: dbpassword
      DB_NAME: dbname
